
import Nav from "./(components)/Nav";
import "./globals.css";

export const metadata = {
  title: "Helio Sal Auth",
  description: "Generated by Helio Sal Corporation",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-emerald-100">
        <Nav />
        <div className="m-2">
          {children}
        </div>
        </body>
    </html>
  );
}
